impl AVPixelFormat {
    pub const AV_PIX_FMT_Y400A: AVPixelFormat = AVPixelFormat::AV_PIX_FMT_YA8;
}
impl AVPixelFormat {
    pub const AV_PIX_FMT_GRAY8A: AVPixelFormat = AVPixelFormat::AV_PIX_FMT_YA8;
}
impl AVPixelFormat {
    pub const AV_PIX_FMT_GBR24P: AVPixelFormat = AVPixelFormat::AV_PIX_FMT_GBRP;
}
#[repr(i32)]
#[doc = " Pixel format.\n\n @note\n AV_PIX_FMT_RGB32 is handled in an endian-specific manner. An RGBA\n color is put together as:\n  (A << 24) | (R << 16) | (G << 8) | B\n This is stored as BGRA on little-endian CPU architectures and ARGB on\n big-endian CPUs.\n\n @note\n If the resolution is not a multiple of the chroma subsampling factor\n then the chroma plane resolution must be rounded up.\n\n @par\n When the pixel format is palettized RGB32 (AV_PIX_FMT_PAL8), the palettized\n image data is stored in AVFrame.data[0]. The palette is transported in\n AVFrame.data[1], is 1024 bytes long (256 4-byte entries) and is\n formatted the same as in AV_PIX_FMT_RGB32 described above (i.e., it is\n also endian-specific). Note also that the individual RGB32 palette\n components stored in AVFrame.data[1] should be in the range 0..255.\n This is important as many custom PAL8 video codecs that were designed\n to run on the IBM VGA graphics adapter use 6-bit palette components.\n\n @par\n For all the 8 bits per pixel formats, an RGB32 palette is in data[1] like\n for pal8. This palette is filled in automatically by the function\n allocating the picture."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum AVPixelFormat {
    AV_PIX_FMT_NONE = -1,
    #[doc = "< planar YUV 4:2:0, 12bpp, (1 Cr & Cb sample per 2x2 Y samples)"]
    AV_PIX_FMT_YUV420P = 0,
    #[doc = "< packed YUV 4:2:2, 16bpp, Y0 Cb Y1 Cr"]
    AV_PIX_FMT_YUYV422 = 1,
    #[doc = "< packed RGB 8:8:8, 24bpp, RGBRGB..."]
    AV_PIX_FMT_RGB24 = 2,
    #[doc = "< packed RGB 8:8:8, 24bpp, BGRBGR..."]
    AV_PIX_FMT_BGR24 = 3,
    #[doc = "< planar YUV 4:2:2, 16bpp, (1 Cr & Cb sample per 2x1 Y samples)"]
    AV_PIX_FMT_YUV422P = 4,
    #[doc = "< planar YUV 4:4:4, 24bpp, (1 Cr & Cb sample per 1x1 Y samples)"]
    AV_PIX_FMT_YUV444P = 5,
    #[doc = "< planar YUV 4:1:0,  9bpp, (1 Cr & Cb sample per 4x4 Y samples)"]
    AV_PIX_FMT_YUV410P = 6,
    #[doc = "< planar YUV 4:1:1, 12bpp, (1 Cr & Cb sample per 4x1 Y samples)"]
    AV_PIX_FMT_YUV411P = 7,
    #[doc = "<        Y        ,  8bpp"]
    AV_PIX_FMT_GRAY8 = 8,
    #[doc = "<        Y        ,  1bpp, 0 is white, 1 is black, in each byte pixels are ordered from the msb to the lsb"]
    AV_PIX_FMT_MONOWHITE = 9,
    #[doc = "<        Y        ,  1bpp, 0 is black, 1 is white, in each byte pixels are ordered from the msb to the lsb"]
    AV_PIX_FMT_MONOBLACK = 10,
    #[doc = "< 8 bits with AV_PIX_FMT_RGB32 palette"]
    AV_PIX_FMT_PAL8 = 11,
    #[doc = "< planar YUV 4:2:0, 12bpp, full scale (JPEG), deprecated in favor of AV_PIX_FMT_YUV420P and setting color_range"]
    AV_PIX_FMT_YUVJ420P = 12,
    #[doc = "< planar YUV 4:2:2, 16bpp, full scale (JPEG), deprecated in favor of AV_PIX_FMT_YUV422P and setting color_range"]
    AV_PIX_FMT_YUVJ422P = 13,
    #[doc = "< planar YUV 4:4:4, 24bpp, full scale (JPEG), deprecated in favor of AV_PIX_FMT_YUV444P and setting color_range"]
    AV_PIX_FMT_YUVJ444P = 14,
    #[doc = "< packed YUV 4:2:2, 16bpp, Cb Y0 Cr Y1"]
    AV_PIX_FMT_UYVY422 = 15,
    #[doc = "< packed YUV 4:1:1, 12bpp, Cb Y0 Y1 Cr Y2 Y3"]
    AV_PIX_FMT_UYYVYY411 = 16,
    #[doc = "< packed RGB 3:3:2,  8bpp, (msb)2B 3G 3R(lsb)"]
    AV_PIX_FMT_BGR8 = 17,
    #[doc = "< packed RGB 1:2:1 bitstream,  4bpp, (msb)1B 2G 1R(lsb), a byte contains two pixels, the first pixel in the byte is the one composed by the 4 msb bits"]
    AV_PIX_FMT_BGR4 = 18,
    #[doc = "< packed RGB 1:2:1,  8bpp, (msb)1B 2G 1R(lsb)"]
    AV_PIX_FMT_BGR4_BYTE = 19,
    #[doc = "< packed RGB 3:3:2,  8bpp, (msb)2R 3G 3B(lsb)"]
    AV_PIX_FMT_RGB8 = 20,
    #[doc = "< packed RGB 1:2:1 bitstream,  4bpp, (msb)1R 2G 1B(lsb), a byte contains two pixels, the first pixel in the byte is the one composed by the 4 msb bits"]
    AV_PIX_FMT_RGB4 = 21,
    #[doc = "< packed RGB 1:2:1,  8bpp, (msb)1R 2G 1B(lsb)"]
    AV_PIX_FMT_RGB4_BYTE = 22,
    #[doc = "< planar YUV 4:2:0, 12bpp, 1 plane for Y and 1 plane for the UV components, which are interleaved (first byte U and the following byte V)"]
    AV_PIX_FMT_NV12 = 23,
    #[doc = "< as above, but U and V bytes are swapped"]
    AV_PIX_FMT_NV21 = 24,
    #[doc = "< packed ARGB 8:8:8:8, 32bpp, ARGBARGB..."]
    AV_PIX_FMT_ARGB = 25,
    #[doc = "< packed RGBA 8:8:8:8, 32bpp, RGBARGBA..."]
    AV_PIX_FMT_RGBA = 26,
    #[doc = "< packed ABGR 8:8:8:8, 32bpp, ABGRABGR..."]
    AV_PIX_FMT_ABGR = 27,
    #[doc = "< packed BGRA 8:8:8:8, 32bpp, BGRABGRA..."]
    AV_PIX_FMT_BGRA = 28,
    #[doc = "<        Y        , 16bpp, big-endian"]
    AV_PIX_FMT_GRAY16BE = 29,
    #[doc = "<        Y        , 16bpp, little-endian"]
    AV_PIX_FMT_GRAY16LE = 30,
    #[doc = "< planar YUV 4:4:0 (1 Cr & Cb sample per 1x2 Y samples)"]
    AV_PIX_FMT_YUV440P = 31,
    #[doc = "< planar YUV 4:4:0 full scale (JPEG), deprecated in favor of AV_PIX_FMT_YUV440P and setting color_range"]
    AV_PIX_FMT_YUVJ440P = 32,
    #[doc = "< planar YUV 4:2:0, 20bpp, (1 Cr & Cb sample per 2x2 Y & A samples)"]
    AV_PIX_FMT_YUVA420P = 33,
    #[doc = "< packed RGB 16:16:16, 48bpp, 16R, 16G, 16B, the 2-byte value for each R/G/B component is stored as big-endian"]
    AV_PIX_FMT_RGB48BE = 34,
    #[doc = "< packed RGB 16:16:16, 48bpp, 16R, 16G, 16B, the 2-byte value for each R/G/B component is stored as little-endian"]
    AV_PIX_FMT_RGB48LE = 35,
    #[doc = "< packed RGB 5:6:5, 16bpp, (msb)   5R 6G 5B(lsb), big-endian"]
    AV_PIX_FMT_RGB565BE = 36,
    #[doc = "< packed RGB 5:6:5, 16bpp, (msb)   5R 6G 5B(lsb), little-endian"]
    AV_PIX_FMT_RGB565LE = 37,
    #[doc = "< packed RGB 5:5:5, 16bpp, (msb)1X 5R 5G 5B(lsb), big-endian   , X=unused/undefined"]
    AV_PIX_FMT_RGB555BE = 38,
    #[doc = "< packed RGB 5:5:5, 16bpp, (msb)1X 5R 5G 5B(lsb), little-endian, X=unused/undefined"]
    AV_PIX_FMT_RGB555LE = 39,
    #[doc = "< packed BGR 5:6:5, 16bpp, (msb)   5B 6G 5R(lsb), big-endian"]
    AV_PIX_FMT_BGR565BE = 40,
    #[doc = "< packed BGR 5:6:5, 16bpp, (msb)   5B 6G 5R(lsb), little-endian"]
    AV_PIX_FMT_BGR565LE = 41,
    #[doc = "< packed BGR 5:5:5, 16bpp, (msb)1X 5B 5G 5R(lsb), big-endian   , X=unused/undefined"]
    AV_PIX_FMT_BGR555BE = 42,
    #[doc = "< packed BGR 5:5:5, 16bpp, (msb)1X 5B 5G 5R(lsb), little-endian, X=unused/undefined"]
    AV_PIX_FMT_BGR555LE = 43,
    #[doc = "  Hardware acceleration through VA-API, data[3] contains a\n  VASurfaceID."]
    AV_PIX_FMT_VAAPI = 44,
    #[doc = "< planar YUV 4:2:0, 24bpp, (1 Cr & Cb sample per 2x2 Y samples), little-endian"]
    AV_PIX_FMT_YUV420P16LE = 45,
    #[doc = "< planar YUV 4:2:0, 24bpp, (1 Cr & Cb sample per 2x2 Y samples), big-endian"]
    AV_PIX_FMT_YUV420P16BE = 46,
    #[doc = "< planar YUV 4:2:2, 32bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian"]
    AV_PIX_FMT_YUV422P16LE = 47,
    #[doc = "< planar YUV 4:2:2, 32bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian"]
    AV_PIX_FMT_YUV422P16BE = 48,
    #[doc = "< planar YUV 4:4:4, 48bpp, (1 Cr & Cb sample per 1x1 Y samples), little-endian"]
    AV_PIX_FMT_YUV444P16LE = 49,
    #[doc = "< planar YUV 4:4:4, 48bpp, (1 Cr & Cb sample per 1x1 Y samples), big-endian"]
    AV_PIX_FMT_YUV444P16BE = 50,
    #[doc = "< HW decoding through DXVA2, Picture.data[3] contains a LPDIRECT3DSURFACE9 pointer"]
    AV_PIX_FMT_DXVA2_VLD = 51,
    #[doc = "< packed RGB 4:4:4, 16bpp, (msb)4X 4R 4G 4B(lsb), little-endian, X=unused/undefined"]
    AV_PIX_FMT_RGB444LE = 52,
    #[doc = "< packed RGB 4:4:4, 16bpp, (msb)4X 4R 4G 4B(lsb), big-endian,    X=unused/undefined"]
    AV_PIX_FMT_RGB444BE = 53,
    #[doc = "< packed BGR 4:4:4, 16bpp, (msb)4X 4B 4G 4R(lsb), little-endian, X=unused/undefined"]
    AV_PIX_FMT_BGR444LE = 54,
    #[doc = "< packed BGR 4:4:4, 16bpp, (msb)4X 4B 4G 4R(lsb), big-endian,    X=unused/undefined"]
    AV_PIX_FMT_BGR444BE = 55,
    #[doc = "< 8 bits gray, 8 bits alpha"]
    AV_PIX_FMT_YA8 = 56,
    #[doc = "< packed RGB 16:16:16, 48bpp, 16B, 16G, 16R, the 2-byte value for each R/G/B component is stored as big-endian"]
    AV_PIX_FMT_BGR48BE = 57,
    #[doc = "< packed RGB 16:16:16, 48bpp, 16B, 16G, 16R, the 2-byte value for each R/G/B component is stored as little-endian"]
    AV_PIX_FMT_BGR48LE = 58,
    #[doc = "< planar YUV 4:2:0, 13.5bpp, (1 Cr & Cb sample per 2x2 Y samples), big-endian"]
    AV_PIX_FMT_YUV420P9BE = 59,
    #[doc = "< planar YUV 4:2:0, 13.5bpp, (1 Cr & Cb sample per 2x2 Y samples), little-endian"]
    AV_PIX_FMT_YUV420P9LE = 60,
    #[doc = "< planar YUV 4:2:0, 15bpp, (1 Cr & Cb sample per 2x2 Y samples), big-endian"]
    AV_PIX_FMT_YUV420P10BE = 61,
    #[doc = "< planar YUV 4:2:0, 15bpp, (1 Cr & Cb sample per 2x2 Y samples), little-endian"]
    AV_PIX_FMT_YUV420P10LE = 62,
    #[doc = "< planar YUV 4:2:2, 20bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian"]
    AV_PIX_FMT_YUV422P10BE = 63,
    #[doc = "< planar YUV 4:2:2, 20bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian"]
    AV_PIX_FMT_YUV422P10LE = 64,
    #[doc = "< planar YUV 4:4:4, 27bpp, (1 Cr & Cb sample per 1x1 Y samples), big-endian"]
    AV_PIX_FMT_YUV444P9BE = 65,
    #[doc = "< planar YUV 4:4:4, 27bpp, (1 Cr & Cb sample per 1x1 Y samples), little-endian"]
    AV_PIX_FMT_YUV444P9LE = 66,
    #[doc = "< planar YUV 4:4:4, 30bpp, (1 Cr & Cb sample per 1x1 Y samples), big-endian"]
    AV_PIX_FMT_YUV444P10BE = 67,
    #[doc = "< planar YUV 4:4:4, 30bpp, (1 Cr & Cb sample per 1x1 Y samples), little-endian"]
    AV_PIX_FMT_YUV444P10LE = 68,
    #[doc = "< planar YUV 4:2:2, 18bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian"]
    AV_PIX_FMT_YUV422P9BE = 69,
    #[doc = "< planar YUV 4:2:2, 18bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian"]
    AV_PIX_FMT_YUV422P9LE = 70,
    #[doc = "< planar GBR 4:4:4 24bpp"]
    AV_PIX_FMT_GBRP = 71,
    #[doc = "< planar GBR 4:4:4 27bpp, big-endian"]
    AV_PIX_FMT_GBRP9BE = 72,
    #[doc = "< planar GBR 4:4:4 27bpp, little-endian"]
    AV_PIX_FMT_GBRP9LE = 73,
    #[doc = "< planar GBR 4:4:4 30bpp, big-endian"]
    AV_PIX_FMT_GBRP10BE = 74,
    #[doc = "< planar GBR 4:4:4 30bpp, little-endian"]
    AV_PIX_FMT_GBRP10LE = 75,
    #[doc = "< planar GBR 4:4:4 48bpp, big-endian"]
    AV_PIX_FMT_GBRP16BE = 76,
    #[doc = "< planar GBR 4:4:4 48bpp, little-endian"]
    AV_PIX_FMT_GBRP16LE = 77,
    #[doc = "< planar YUV 4:2:2 24bpp, (1 Cr & Cb sample per 2x1 Y & A samples)"]
    AV_PIX_FMT_YUVA422P = 78,
    #[doc = "< planar YUV 4:4:4 32bpp, (1 Cr & Cb sample per 1x1 Y & A samples)"]
    AV_PIX_FMT_YUVA444P = 79,
    #[doc = "< planar YUV 4:2:0 22.5bpp, (1 Cr & Cb sample per 2x2 Y & A samples), big-endian"]
    AV_PIX_FMT_YUVA420P9BE = 80,
    #[doc = "< planar YUV 4:2:0 22.5bpp, (1 Cr & Cb sample per 2x2 Y & A samples), little-endian"]
    AV_PIX_FMT_YUVA420P9LE = 81,
    #[doc = "< planar YUV 4:2:2 27bpp, (1 Cr & Cb sample per 2x1 Y & A samples), big-endian"]
    AV_PIX_FMT_YUVA422P9BE = 82,
    #[doc = "< planar YUV 4:2:2 27bpp, (1 Cr & Cb sample per 2x1 Y & A samples), little-endian"]
    AV_PIX_FMT_YUVA422P9LE = 83,
    #[doc = "< planar YUV 4:4:4 36bpp, (1 Cr & Cb sample per 1x1 Y & A samples), big-endian"]
    AV_PIX_FMT_YUVA444P9BE = 84,
    #[doc = "< planar YUV 4:4:4 36bpp, (1 Cr & Cb sample per 1x1 Y & A samples), little-endian"]
    AV_PIX_FMT_YUVA444P9LE = 85,
    #[doc = "< planar YUV 4:2:0 25bpp, (1 Cr & Cb sample per 2x2 Y & A samples, big-endian)"]
    AV_PIX_FMT_YUVA420P10BE = 86,
    #[doc = "< planar YUV 4:2:0 25bpp, (1 Cr & Cb sample per 2x2 Y & A samples, little-endian)"]
    AV_PIX_FMT_YUVA420P10LE = 87,
    #[doc = "< planar YUV 4:2:2 30bpp, (1 Cr & Cb sample per 2x1 Y & A samples, big-endian)"]
    AV_PIX_FMT_YUVA422P10BE = 88,
    #[doc = "< planar YUV 4:2:2 30bpp, (1 Cr & Cb sample per 2x1 Y & A samples, little-endian)"]
    AV_PIX_FMT_YUVA422P10LE = 89,
    #[doc = "< planar YUV 4:4:4 40bpp, (1 Cr & Cb sample per 1x1 Y & A samples, big-endian)"]
    AV_PIX_FMT_YUVA444P10BE = 90,
    #[doc = "< planar YUV 4:4:4 40bpp, (1 Cr & Cb sample per 1x1 Y & A samples, little-endian)"]
    AV_PIX_FMT_YUVA444P10LE = 91,
    #[doc = "< planar YUV 4:2:0 40bpp, (1 Cr & Cb sample per 2x2 Y & A samples, big-endian)"]
    AV_PIX_FMT_YUVA420P16BE = 92,
    #[doc = "< planar YUV 4:2:0 40bpp, (1 Cr & Cb sample per 2x2 Y & A samples, little-endian)"]
    AV_PIX_FMT_YUVA420P16LE = 93,
    #[doc = "< planar YUV 4:2:2 48bpp, (1 Cr & Cb sample per 2x1 Y & A samples, big-endian)"]
    AV_PIX_FMT_YUVA422P16BE = 94,
    #[doc = "< planar YUV 4:2:2 48bpp, (1 Cr & Cb sample per 2x1 Y & A samples, little-endian)"]
    AV_PIX_FMT_YUVA422P16LE = 95,
    #[doc = "< planar YUV 4:4:4 64bpp, (1 Cr & Cb sample per 1x1 Y & A samples, big-endian)"]
    AV_PIX_FMT_YUVA444P16BE = 96,
    #[doc = "< planar YUV 4:4:4 64bpp, (1 Cr & Cb sample per 1x1 Y & A samples, little-endian)"]
    AV_PIX_FMT_YUVA444P16LE = 97,
    #[doc = "< HW acceleration through VDPAU, Picture.data[3] contains a VdpVideoSurface"]
    AV_PIX_FMT_VDPAU = 98,
    #[doc = "< packed XYZ 4:4:4, 36 bpp, (msb) 12X, 12Y, 12Z (lsb), the 2-byte value for each X/Y/Z is stored as little-endian, the 4 lower bits are set to 0"]
    AV_PIX_FMT_XYZ12LE = 99,
    #[doc = "< packed XYZ 4:4:4, 36 bpp, (msb) 12X, 12Y, 12Z (lsb), the 2-byte value for each X/Y/Z is stored as big-endian, the 4 lower bits are set to 0"]
    AV_PIX_FMT_XYZ12BE = 100,
    #[doc = "< interleaved chroma YUV 4:2:2, 16bpp, (1 Cr & Cb sample per 2x1 Y samples)"]
    AV_PIX_FMT_NV16 = 101,
    #[doc = "< interleaved chroma YUV 4:2:2, 20bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian"]
    AV_PIX_FMT_NV20LE = 102,
    #[doc = "< interleaved chroma YUV 4:2:2, 20bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian"]
    AV_PIX_FMT_NV20BE = 103,
    #[doc = "< packed RGBA 16:16:16:16, 64bpp, 16R, 16G, 16B, 16A, the 2-byte value for each R/G/B/A component is stored as big-endian"]
    AV_PIX_FMT_RGBA64BE = 104,
    #[doc = "< packed RGBA 16:16:16:16, 64bpp, 16R, 16G, 16B, 16A, the 2-byte value for each R/G/B/A component is stored as little-endian"]
    AV_PIX_FMT_RGBA64LE = 105,
    #[doc = "< packed RGBA 16:16:16:16, 64bpp, 16B, 16G, 16R, 16A, the 2-byte value for each R/G/B/A component is stored as big-endian"]
    AV_PIX_FMT_BGRA64BE = 106,
    #[doc = "< packed RGBA 16:16:16:16, 64bpp, 16B, 16G, 16R, 16A, the 2-byte value for each R/G/B/A component is stored as little-endian"]
    AV_PIX_FMT_BGRA64LE = 107,
    #[doc = "< packed YUV 4:2:2, 16bpp, Y0 Cr Y1 Cb"]
    AV_PIX_FMT_YVYU422 = 108,
    #[doc = "< 16 bits gray, 16 bits alpha (big-endian)"]
    AV_PIX_FMT_YA16BE = 109,
    #[doc = "< 16 bits gray, 16 bits alpha (little-endian)"]
    AV_PIX_FMT_YA16LE = 110,
    #[doc = "< planar GBRA 4:4:4:4 32bpp"]
    AV_PIX_FMT_GBRAP = 111,
    #[doc = "< planar GBRA 4:4:4:4 64bpp, big-endian"]
    AV_PIX_FMT_GBRAP16BE = 112,
    #[doc = "< planar GBRA 4:4:4:4 64bpp, little-endian"]
    AV_PIX_FMT_GBRAP16LE = 113,
    #[doc = "  HW acceleration through QSV, data[3] contains a pointer to the\n  mfxFrameSurface1 structure."]
    AV_PIX_FMT_QSV = 114,
    #[doc = " HW acceleration though MMAL, data[3] contains a pointer to the\n MMAL_BUFFER_HEADER_T structure."]
    AV_PIX_FMT_MMAL = 115,
    #[doc = "< HW decoding through Direct3D11 via old API, Picture.data[3] contains a ID3D11VideoDecoderOutputView pointer"]
    AV_PIX_FMT_D3D11VA_VLD = 116,
    #[doc = " HW acceleration through CUDA. data[i] contain CUdeviceptr pointers\n exactly as for system memory frames."]
    AV_PIX_FMT_CUDA = 117,
    #[doc = "< packed RGB 8:8:8, 32bpp, XRGBXRGB...   X=unused/undefined"]
    AV_PIX_FMT_0RGB = 118,
    #[doc = "< packed RGB 8:8:8, 32bpp, RGBXRGBX...   X=unused/undefined"]
    AV_PIX_FMT_RGB0 = 119,
    #[doc = "< packed BGR 8:8:8, 32bpp, XBGRXBGR...   X=unused/undefined"]
    AV_PIX_FMT_0BGR = 120,
    #[doc = "< packed BGR 8:8:8, 32bpp, BGRXBGRX...   X=unused/undefined"]
    AV_PIX_FMT_BGR0 = 121,
    #[doc = "< planar YUV 4:2:0,18bpp, (1 Cr & Cb sample per 2x2 Y samples), big-endian"]
    AV_PIX_FMT_YUV420P12BE = 122,
    #[doc = "< planar YUV 4:2:0,18bpp, (1 Cr & Cb sample per 2x2 Y samples), little-endian"]
    AV_PIX_FMT_YUV420P12LE = 123,
    #[doc = "< planar YUV 4:2:0,21bpp, (1 Cr & Cb sample per 2x2 Y samples), big-endian"]
    AV_PIX_FMT_YUV420P14BE = 124,
    #[doc = "< planar YUV 4:2:0,21bpp, (1 Cr & Cb sample per 2x2 Y samples), little-endian"]
    AV_PIX_FMT_YUV420P14LE = 125,
    #[doc = "< planar YUV 4:2:2,24bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian"]
    AV_PIX_FMT_YUV422P12BE = 126,
    #[doc = "< planar YUV 4:2:2,24bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian"]
    AV_PIX_FMT_YUV422P12LE = 127,
    #[doc = "< planar YUV 4:2:2,28bpp, (1 Cr & Cb sample per 2x1 Y samples), big-endian"]
    AV_PIX_FMT_YUV422P14BE = 128,
    #[doc = "< planar YUV 4:2:2,28bpp, (1 Cr & Cb sample per 2x1 Y samples), little-endian"]
    AV_PIX_FMT_YUV422P14LE = 129,
    #[doc = "< planar YUV 4:4:4,36bpp, (1 Cr & Cb sample per 1x1 Y samples), big-endian"]
    AV_PIX_FMT_YUV444P12BE = 130,
    #[doc = "< planar YUV 4:4:4,36bpp, (1 Cr & Cb sample per 1x1 Y samples), little-endian"]
    AV_PIX_FMT_YUV444P12LE = 131,
    #[doc = "< planar YUV 4:4:4,42bpp, (1 Cr & Cb sample per 1x1 Y samples), big-endian"]
    AV_PIX_FMT_YUV444P14BE = 132,
    #[doc = "< planar YUV 4:4:4,42bpp, (1 Cr & Cb sample per 1x1 Y samples), little-endian"]
    AV_PIX_FMT_YUV444P14LE = 133,
    #[doc = "< planar GBR 4:4:4 36bpp, big-endian"]
    AV_PIX_FMT_GBRP12BE = 134,
    #[doc = "< planar GBR 4:4:4 36bpp, little-endian"]
    AV_PIX_FMT_GBRP12LE = 135,
    #[doc = "< planar GBR 4:4:4 42bpp, big-endian"]
    AV_PIX_FMT_GBRP14BE = 136,
    #[doc = "< planar GBR 4:4:4 42bpp, little-endian"]
    AV_PIX_FMT_GBRP14LE = 137,
    #[doc = "< planar YUV 4:1:1, 12bpp, (1 Cr & Cb sample per 4x1 Y samples) full scale (JPEG), deprecated in favor of AV_PIX_FMT_YUV411P and setting color_range"]
    AV_PIX_FMT_YUVJ411P = 138,
    #[doc = "< bayer, BGBG..(odd line), GRGR..(even line), 8-bit samples"]
    AV_PIX_FMT_BAYER_BGGR8 = 139,
    #[doc = "< bayer, RGRG..(odd line), GBGB..(even line), 8-bit samples"]
    AV_PIX_FMT_BAYER_RGGB8 = 140,
    #[doc = "< bayer, GBGB..(odd line), RGRG..(even line), 8-bit samples"]
    AV_PIX_FMT_BAYER_GBRG8 = 141,
    #[doc = "< bayer, GRGR..(odd line), BGBG..(even line), 8-bit samples"]
    AV_PIX_FMT_BAYER_GRBG8 = 142,
    #[doc = "< bayer, BGBG..(odd line), GRGR..(even line), 16-bit samples, little-endian"]
    AV_PIX_FMT_BAYER_BGGR16LE = 143,
    #[doc = "< bayer, BGBG..(odd line), GRGR..(even line), 16-bit samples, big-endian"]
    AV_PIX_FMT_BAYER_BGGR16BE = 144,
    #[doc = "< bayer, RGRG..(odd line), GBGB..(even line), 16-bit samples, little-endian"]
    AV_PIX_FMT_BAYER_RGGB16LE = 145,
    #[doc = "< bayer, RGRG..(odd line), GBGB..(even line), 16-bit samples, big-endian"]
    AV_PIX_FMT_BAYER_RGGB16BE = 146,
    #[doc = "< bayer, GBGB..(odd line), RGRG..(even line), 16-bit samples, little-endian"]
    AV_PIX_FMT_BAYER_GBRG16LE = 147,
    #[doc = "< bayer, GBGB..(odd line), RGRG..(even line), 16-bit samples, big-endian"]
    AV_PIX_FMT_BAYER_GBRG16BE = 148,
    #[doc = "< bayer, GRGR..(odd line), BGBG..(even line), 16-bit samples, little-endian"]
    AV_PIX_FMT_BAYER_GRBG16LE = 149,
    #[doc = "< bayer, GRGR..(odd line), BGBG..(even line), 16-bit samples, big-endian"]
    AV_PIX_FMT_BAYER_GRBG16BE = 150,
    #[doc = "< XVideo Motion Acceleration via common packet passing"]
    AV_PIX_FMT_XVMC = 151,
    #[doc = "< planar YUV 4:4:0,20bpp, (1 Cr & Cb sample per 1x2 Y samples), little-endian"]
    AV_PIX_FMT_YUV440P10LE = 152,
    #[doc = "< planar YUV 4:4:0,20bpp, (1 Cr & Cb sample per 1x2 Y samples), big-endian"]
    AV_PIX_FMT_YUV440P10BE = 153,
    #[doc = "< planar YUV 4:4:0,24bpp, (1 Cr & Cb sample per 1x2 Y samples), little-endian"]
    AV_PIX_FMT_YUV440P12LE = 154,
    #[doc = "< planar YUV 4:4:0,24bpp, (1 Cr & Cb sample per 1x2 Y samples), big-endian"]
    AV_PIX_FMT_YUV440P12BE = 155,
    #[doc = "< packed AYUV 4:4:4,64bpp (1 Cr & Cb sample per 1x1 Y & A samples), little-endian"]
    AV_PIX_FMT_AYUV64LE = 156,
    #[doc = "< packed AYUV 4:4:4,64bpp (1 Cr & Cb sample per 1x1 Y & A samples), big-endian"]
    AV_PIX_FMT_AYUV64BE = 157,
    #[doc = "< hardware decoding through Videotoolbox"]
    AV_PIX_FMT_VIDEOTOOLBOX = 158,
    #[doc = "< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, little-endian"]
    AV_PIX_FMT_P010LE = 159,
    #[doc = "< like NV12, with 10bpp per component, data in the high bits, zeros in the low bits, big-endian"]
    AV_PIX_FMT_P010BE = 160,
    #[doc = "< planar GBR 4:4:4:4 48bpp, big-endian"]
    AV_PIX_FMT_GBRAP12BE = 161,
    #[doc = "< planar GBR 4:4:4:4 48bpp, little-endian"]
    AV_PIX_FMT_GBRAP12LE = 162,
    #[doc = "< planar GBR 4:4:4:4 40bpp, big-endian"]
    AV_PIX_FMT_GBRAP10BE = 163,
    #[doc = "< planar GBR 4:4:4:4 40bpp, little-endian"]
    AV_PIX_FMT_GBRAP10LE = 164,
    #[doc = "< hardware decoding through MediaCodec"]
    AV_PIX_FMT_MEDIACODEC = 165,
    #[doc = "<        Y        , 12bpp, big-endian"]
    AV_PIX_FMT_GRAY12BE = 166,
    #[doc = "<        Y        , 12bpp, little-endian"]
    AV_PIX_FMT_GRAY12LE = 167,
    #[doc = "<        Y        , 10bpp, big-endian"]
    AV_PIX_FMT_GRAY10BE = 168,
    #[doc = "<        Y        , 10bpp, little-endian"]
    AV_PIX_FMT_GRAY10LE = 169,
    #[doc = "< like NV12, with 16bpp per component, little-endian"]
    AV_PIX_FMT_P016LE = 170,
    #[doc = "< like NV12, with 16bpp per component, big-endian"]
    AV_PIX_FMT_P016BE = 171,
    #[doc = " Hardware surfaces for Direct3D11.\n\n This is preferred over the legacy AV_PIX_FMT_D3D11VA_VLD. The new D3D11\n hwaccel API and filtering support AV_PIX_FMT_D3D11 only.\n\n data[0] contains a ID3D11Texture2D pointer, and data[1] contains the\n texture array index of the frame as intptr_t if the ID3D11Texture2D is\n an array texture (or always 0 if it's a normal texture)."]
    AV_PIX_FMT_D3D11 = 172,
    #[doc = "<        Y        , 9bpp, big-endian"]
    AV_PIX_FMT_GRAY9BE = 173,
    #[doc = "<        Y        , 9bpp, little-endian"]
    AV_PIX_FMT_GRAY9LE = 174,
    #[doc = "< IEEE-754 single precision planar GBR 4:4:4,     96bpp, big-endian"]
    AV_PIX_FMT_GBRPF32BE = 175,
    #[doc = "< IEEE-754 single precision planar GBR 4:4:4,     96bpp, little-endian"]
    AV_PIX_FMT_GBRPF32LE = 176,
    #[doc = "< IEEE-754 single precision planar GBRA 4:4:4:4, 128bpp, big-endian"]
    AV_PIX_FMT_GBRAPF32BE = 177,
    #[doc = "< IEEE-754 single precision planar GBRA 4:4:4:4, 128bpp, little-endian"]
    AV_PIX_FMT_GBRAPF32LE = 178,
    #[doc = " DRM-managed buffers exposed through PRIME buffer sharing.\n\n data[0] points to an AVDRMFrameDescriptor."]
    AV_PIX_FMT_DRM_PRIME = 179,
    #[doc = " Hardware surfaces for OpenCL.\n\n data[i] contain 2D image objects (typed in C as cl_mem, used\n in OpenCL as image2d_t) for each plane of the surface."]
    AV_PIX_FMT_OPENCL = 180,
    #[doc = "<        Y        , 14bpp, big-endian"]
    AV_PIX_FMT_GRAY14BE = 181,
    #[doc = "<        Y        , 14bpp, little-endian"]
    AV_PIX_FMT_GRAY14LE = 182,
    #[doc = "< IEEE-754 single precision Y, 32bpp, big-endian"]
    AV_PIX_FMT_GRAYF32BE = 183,
    #[doc = "< IEEE-754 single precision Y, 32bpp, little-endian"]
    AV_PIX_FMT_GRAYF32LE = 184,
    #[doc = "< planar YUV 4:2:2,24bpp, (1 Cr & Cb sample per 2x1 Y samples), 12b alpha, big-endian"]
    AV_PIX_FMT_YUVA422P12BE = 185,
    #[doc = "< planar YUV 4:2:2,24bpp, (1 Cr & Cb sample per 2x1 Y samples), 12b alpha, little-endian"]
    AV_PIX_FMT_YUVA422P12LE = 186,
    #[doc = "< planar YUV 4:4:4,36bpp, (1 Cr & Cb sample per 1x1 Y samples), 12b alpha, big-endian"]
    AV_PIX_FMT_YUVA444P12BE = 187,
    #[doc = "< planar YUV 4:4:4,36bpp, (1 Cr & Cb sample per 1x1 Y samples), 12b alpha, little-endian"]
    AV_PIX_FMT_YUVA444P12LE = 188,
    #[doc = "< planar YUV 4:4:4, 24bpp, 1 plane for Y and 1 plane for the UV components, which are interleaved (first byte U and the following byte V)"]
    AV_PIX_FMT_NV24 = 189,
    #[doc = "< as above, but U and V bytes are swapped"]
    AV_PIX_FMT_NV42 = 190,
    #[doc = " Vulkan hardware images.\n\n data[0] points to an AVVkFrame"]
    AV_PIX_FMT_VULKAN = 191,
    #[doc = "< packed YUV 4:2:2 like YUYV422, 20bpp, data in the high bits, big-endian"]
    AV_PIX_FMT_Y210BE = 192,
    #[doc = "< packed YUV 4:2:2 like YUYV422, 20bpp, data in the high bits, little-endian"]
    AV_PIX_FMT_Y210LE = 193,
    #[doc = "< packed RGB 10:10:10, 30bpp, (msb)2X 10R 10G 10B(lsb), little-endian, X=unused/undefined"]
    AV_PIX_FMT_X2RGB10LE = 194,
    #[doc = "< packed RGB 10:10:10, 30bpp, (msb)2X 10R 10G 10B(lsb), big-endian, X=unused/undefined"]
    AV_PIX_FMT_X2RGB10BE = 195,
    #[doc = "< packed BGR 10:10:10, 30bpp, (msb)2X 10B 10G 10R(lsb), little-endian, X=unused/undefined"]
    AV_PIX_FMT_X2BGR10LE = 196,
    #[doc = "< packed BGR 10:10:10, 30bpp, (msb)2X 10B 10G 10R(lsb), big-endian, X=unused/undefined"]
    AV_PIX_FMT_X2BGR10BE = 197,
    #[doc = "< interleaved chroma YUV 4:2:2, 20bpp, data in the high bits, big-endian"]
    AV_PIX_FMT_P210BE = 198,
    #[doc = "< interleaved chroma YUV 4:2:2, 20bpp, data in the high bits, little-endian"]
    AV_PIX_FMT_P210LE = 199,
    #[doc = "< interleaved chroma YUV 4:4:4, 30bpp, data in the high bits, big-endian"]
    AV_PIX_FMT_P410BE = 200,
    #[doc = "< interleaved chroma YUV 4:4:4, 30bpp, data in the high bits, little-endian"]
    AV_PIX_FMT_P410LE = 201,
    #[doc = "< interleaved chroma YUV 4:2:2, 32bpp, big-endian"]
    AV_PIX_FMT_P216BE = 202,
    #[doc = "< interleaved chroma YUV 4:2:2, 32bpp, little-endian"]
    AV_PIX_FMT_P216LE = 203,
    #[doc = "< interleaved chroma YUV 4:4:4, 48bpp, big-endian"]
    AV_PIX_FMT_P416BE = 204,
    #[doc = "< interleaved chroma YUV 4:4:4, 48bpp, little-endian"]
    AV_PIX_FMT_P416LE = 205,
    #[doc = "< number of pixel formats, DO NOT USE THIS if you want to link with shared libav* because the number of formats might differ between versions"]
    AV_PIX_FMT_NB = 206,
}
