[package]
name = "ac-ffmpeg"
version = "0.17.1"
authors = ["Angelcam, Inc. <dev@angelcam.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/ac-ffmpeg/"
repository = "https://github.com/angelcam/rust-ac-ffmpeg"
description = """
Simple and safe Rust interface for FFmpeg libraries.
"""
keywords = ["ffmpeg", "audio", "video", "codec", "multimedia"]

[dependencies]
lazy_static = "1.4"
serde = { version = "1.0", optional = true }

[build-dependencies]
cc         = "1.0"
pkg-config = "0.3.16"

[dev-dependencies]
clap = "2.33"

[features]
default = []
serde = ["dep:serde"]